In [81]:
import numpy as np

# Importing standard Qiskit libraries
from qiskit import QuantumCircuit, transpile, Aer, IBMQ
from qiskit.tools.jupyter import *
from qiskit.visualization import *
from ibm_quantum_widgets import *
from qiskit.providers.aer import QasmSimulator

# Loading your IBM Quantum account(s)
provider = IBMQ.load_account()

ibmqfactory.load_account:WARNING:2022-12-04 03:39:17,640: Credentials are already in use. The existing account in the session will be replaced.


In [2]:
!pip install mxnet

     |████████████████████████████████| 49.1 MB 32 kB/s s eta 0:00:01
  Attempting uninstall: graphviz
    Found existing installation: graphviz 0.20.1
    Uninstalling graphviz-0.20.1:
      Successfully uninstalled graphviz-0.20.1


In [3]:


from mxnet import nd


In [8]:
x = nd.array([3.0])
y = nd.array([2.0])

print('x + y = ' ,  x + y)
print('x / y = ' ,  x / y)
print('x * y = ' ,  x * y)
print('x - y = ' ,  x - y)
print('x ** y = ' ,  nd.power(x , y))

x + y =  
[5.]
<NDArray 1 @cpu(0)>
x / y =  
[1.5]
<NDArray 1 @cpu(0)>
x * y =  
[6.]
<NDArray 1 @cpu(0)>
x - y =  
[1.]
<NDArray 1 @cpu(0)>
x ** y =  
[9.]
<NDArray 1 @cpu(0)>


In [10]:
print(x)
print(x.asscalar())


[3.]
<NDArray 1 @cpu(0)>
3.0


In [27]:
x = nd.arange(7)
print('x = ' , x)

x =  
[0. 1. 2. 3. 4. 5. 6.]
<NDArray 7 @cpu(0)>


In [24]:
x[3]


[3.]
<NDArray 1 @cpu(0)>

In [29]:
x.shape

(7,)

In [30]:
a = 2 
x = nd.array([1,2,3])
y = nd.array([10,20,30])
print(a * x)
print(a * x + y)


[2. 4. 6.]
<NDArray 3 @cpu(0)>

[12. 24. 36.]
<NDArray 3 @cpu(0)>


In [83]:
print(nd.arange(10))


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
<NDArray 10 @cpu(0)>


In [84]:
A = A.reshape((3,4))
print(A)

Traceback (most recent call last):
  Input In [84] in <cell line: 1>
    A = A.reshape((3,4))
  File /opt/conda/lib/python3.8/site-packages/mxnet/ndarray/ndarray.py:1524 in reshape
    raise ValueError('Cannot reshape array of size {} into shape {}'.format(np.prod(self.shape), shape))
ValueError: Cannot reshape array of size 20 into shape (3, 4)

Use %tb to get the full traceback.


In [34]:
print(A.T)


[[ 0. 10.]
 [ 1. 11.]
 [ 2. 12.]
 [ 3. 13.]
 [ 4. 14.]
 [ 5. 15.]
 [ 6. 16.]
 [ 7. 17.]
 [ 8. 18.]
 [ 9. 19.]]
<NDArray 10x2 @cpu(0)>


In [38]:
X = nd.arange(24).reshape((2,3,4))
print('X Shape =', X.shape)
X

X Shape = (2, 3, 4)



[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]
<NDArray 2x3x4 @cpu(0)>

In [39]:
print(X.T)


[[[ 0. 12.]
  [ 4. 16.]
  [ 8. 20.]]

 [[ 1. 13.]
  [ 5. 17.]
  [ 9. 21.]]

 [[ 2. 14.]
  [ 6. 18.]
  [10. 22.]]

 [[ 3. 15.]
  [ 7. 19.]
  [11. 23.]]]
<NDArray 4x3x2 @cpu(0)>


In [90]:
a = 2
x = nd.arange(3)
y = nd.arange(3)
print(x.shape)
print(y.shape)
print((a * x).shape)
print((a * x + y).shape)
a
x
y

(3,)
(3,)
(3,)
(3,)



[0. 1. 2.]
<NDArray 3 @cpu(0)>

In [49]:
x = nd.arange(12)
x = x.reshape((3,4))
print(x)
print(nd.sum(x, 1))


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

[ 6. 22. 38.]
<NDArray 3 @cpu(0)>


In [51]:
print(A)
print(nd.sum(A,0))


[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]
<NDArray 2x10 @cpu(0)>

[10. 12. 14. 16. 18. 20. 22. 24. 26. 28.]
<NDArray 10 @cpu(0)>


In [53]:
print(nd.sum(A) / A.size)


[9.5]
<NDArray 1 @cpu(0)>


In [54]:
print(A.size)

20


In [55]:
print(nd.sum(A))


[190.]
<NDArray 1 @cpu(0)>


In [62]:
print([190/20])

[9.5]


In [63]:
print(nd.mean(A))


[9.5]
<NDArray 1 @cpu(0)>


In [69]:
x = nd.arange(4) + 1.0
y = nd.ones(4)
print(x , y , nd.dot(x,y))
print((x * y).sum())
nd.sum(x * y)
print(nd.dot(x, y))


[1. 2. 3. 4.]
<NDArray 4 @cpu(0)> 
[1. 1. 1. 1.]
<NDArray 4 @cpu(0)> 
[10.]
<NDArray 1 @cpu(0)>

[10.]
<NDArray 1 @cpu(0)>

[10.]
<NDArray 1 @cpu(0)>


In [78]:
A = A.reshape((3,4))
print(nd.dot(A, x))
print(A * x)

Traceback (most recent call last):
  Input In [78] in <cell line: 1>
    A = A.reshape((3,4))
  File /opt/conda/lib/python3.8/site-packages/mxnet/ndarray/ndarray.py:1524 in reshape
    raise ValueError('Cannot reshape array of size {} into shape {}'.format(np.prod(self.shape), shape))
ValueError: Cannot reshape array of size 20 into shape (3, 4)

Use %tb to get the full traceback.


In [85]:
B = nd.ones(shape=(4,3))
nd.dot(A,B)

MXNetError: Traceback (most recent call last):
  File "../src/operator/tensor/./dot-inl.h", line 1241
MXNetError: Check failed: L[!Ta].Size() == R[Tb].Size() (10 vs. 4) : dot shape error: [2,10] X [4,3]

Use %tb to get the full traceback.


In [86]:
nd.norm(x)


[5.477226]
<NDArray 1 @cpu(0)>

In [91]:
nd.sum(nd.abs(x))
nd.array(((1,2,3),(5,6,7)))


[[1. 2. 3.]
 [5. 6. 7.]]
<NDArray 2x3 @cpu(0)>

In [92]:

x = nd.ones((2,3))
x


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [93]:
y = nd.random.uniform(-1,1,(2,3))
y


[[0.09762704 0.18568921 0.43037868]
 [0.6885315  0.20552671 0.71589124]]
<NDArray 2x3 @cpu(0)>

In [94]:
x = nd.full((2,3), 2.0)
x


[[2. 2. 2.]
 [2. 2. 2.]]
<NDArray 2x3 @cpu(0)>

In [96]:
(x.shape, x.size, x.dtype)
x * y
y.exp()
nd.dot(x, y.T)
y[1,2]
y[:,1:3]



[[0.18568921 0.43037868]
 [0.20552671 0.71589124]]
<NDArray 2x2 @cpu(0)>

In [98]:
nd.dot(x, y.T)
y[:,1:3] = 2
y


[[0.09762704 2.         2.        ]
 [0.6885315  2.         2.        ]]
<NDArray 2x3 @cpu(0)>

In [99]:
y[1:2,0:2] = 4
y



[[0.09762704 2.         2.        ]
 [4.         4.         2.        ]]
<NDArray 2x3 @cpu(0)>

In [100]:

a = x.asnumpy()
(type(a), a)

(numpy.ndarray,
 array([[2., 2., 2.],
        [2., 2., 2.]], dtype=float32))

In [101]:
nd.array(a)



[[2. 2. 2.]
 [2. 2. 2.]]
<NDArray 2x3 @cpu(0)>

In [102]:

from mxnet import nd
from mxnet.gluon import nn

In [103]:

from mxnet import nd
from mxnet.gluon import nn

In [105]:
layer = nn.Dense(2)
layer


Dense(None -> 2, linear)

In [107]:
layer.initialize()
x = nd.random.uniform(-1,1,(3,4))
layer(x)

/opt/conda/lib/python3.8/site-packages/mxnet/gluon/parameter.py:896: UserWarning: Parameter 'dense0_bias' is already initialized, ignoring. Set force_reinit=True to re-initialize.
  v.initialize(None, ctx, init, force_reinit=force_reinit)



[[ 0.0009278  -0.00674768]
 [-0.02683341  0.00671751]
 [ 0.00798804  0.02131375]]
<NDArray 3x2 @cpu(0)>

In [108]:
layer.weight.data()



[[-0.01631819 -0.00312688  0.0408415   0.04370362]
 [ 0.00404529 -0.0028032   0.00952624 -0.01501013]]
<NDArray 2x4 @cpu(0)>

In [109]:
net = nn.Sequential()
# Add a sequence of layers.
net.add(# Similar to Dense, it is not necessary to specify the input channels
        # by the argument `in_channels`, which will be  automatically inferred
        # in the first forward pass. Also, we apply a relu activation on the
        # output. In addition, we can use a tuple to specify a  non-square
        # kernel size, such as `kernel_size=(2,4)`
        nn.Conv2D(channels=6, kernel_size=(2,4), activation='relu'),
        # One can also use a tuple to specify non-symmetric pool and stride sizes
        nn.MaxPool2D(pool_size=3, strides=5),
        nn.Conv2D(channels=16, kernel_size=3, activation='relu'),
        nn.MaxPool2D(pool_size=2, strides=2),
        # The dense layer will automatically reshape the 4-D output of last
        # max pooling layer into the 2-D shape: (x.shape[0], x.size/x.shape[0])
        nn.Dense(120, activation="relu"),
        nn.Dense(84, activation="relu"),
        nn.Dense(10))
net

Sequential(
  (0): Conv2D(None -> 6, kernel_size=(2, 4), stride=(1, 1), Activation(relu))
  (1): MaxPool2D(size=(3, 3), stride=(5, 5), padding=(0, 0), ceil_mode=False, global_pool=False, pool_type=max, layout=NCHW)
  (2): Conv2D(None -> 16, kernel_size=(3, 3), stride=(1, 1), Activation(relu))
  (3): MaxPool2D(size=(2, 2), stride=(2, 2), padding=(0, 0), ceil_mode=False, global_pool=False, pool_type=max, layout=NCHW)
  (4): Dense(None -> 120, Activation(relu))
  (5): Dense(None -> 84, Activation(relu))
  (6): Dense(None -> 10, linear)
)

In [110]:

net.initialize()
# Input shape is (batch_size, color_channels, height, width)
x = nd.random.uniform(shape=(4,1,28,28))
y = net(x)
y.shape

(4, 10)

In [111]:
(net[0].weight.data().shape, net[5].bias.data().shape)


((6, 1, 2, 4), (84,))

In [156]:
class MixMLP(nn.Block):
    def __init__(self, **kwargs):
        # Run `nn.Block`'s init method
        super(MixMLP, self).__init__(**kwargs)
        self.blk = nn.Sequential()
        self.blk.add(nn.Dense(3, activation='relu'),
                     nn.Dense(4, activation='relu'))
        self.dense = nn.Dense(5)
    def forward(self, x):
        y = nd.relu(self.blk(x))
        print(y)
        return self.dense(y)

net = MixMLP()
net

MixMLP(
  (blk): Sequential(
    (0): Dense(None -> 3, Activation(relu))
    (1): Dense(None -> 4, Activation(relu))
  )
  (dense): Dense(None -> 5, linear)
)

In [139]:
net.initialize()
x = nd.random.uniform(shape=(2,2))
net(x)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 2x4 @cpu(0)>



[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
<NDArray 2x5 @cpu(0)>

In [157]:
print('****************')
net.blk[0].weight.data()


****************
Traceback (most recent call last):
  Input In [157] in <cell line: 2>
    net.blk[0].weight.data()
  File /opt/conda/lib/python3.8/site-packages/mxnet/gluon/parameter.py:574 in data
    return self._check_and_get(self._data, ctx)
  File /opt/conda/lib/python3.8/site-packages/mxnet/gluon/parameter.py:236 in _check_and_get
    raise RuntimeError(
RuntimeError: Parameter 'dense16_weight' has not been initialized. Note that you should initialize parameters and create Trainer with Block.collect_params() instead of Block.params because the later does not include Parameters of nested child Blocks

Use %tb to get the full traceback.


In [140]:

class MixMLP(nn.Block):
    def __init__(self, **kwargs):
        # Run `nn.Block`'s init method
        super(MixMLP, self).__init__(**kwargs)
        self.blk = nn.Sequential()
        self.blk.add(nn.Dense(3, activation='relu'),
                     nn.Dense(4, activation='relu'))
        self.dense = nn.Dense(5)
    def forward(self, x):
        y = nd.relu(self.blk(x))
        print(y)
        return self.dense(y)

net = MixMLP()
net

MixMLP(
  (blk): Sequential(
    (0): Dense(None -> 3, Activation(relu))
    (1): Dense(None -> 4, Activation(relu))
  )
  (dense): Dense(None -> 5, linear)
)

In [143]:
nd.empty((3,4))
nd.zeros((3,4))
nd.ones((3,4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [148]:
nd.random.normal(0, 1, shape=(3,4))


[[-0.92477405 -0.24934843 -0.76926744 -0.52923554]
 [-0.7002489   0.34975412  0.33554974 -0.5138925 ]
 [ 0.20229425 -0.6626633   0.5509831  -0.80002475]]
<NDArray 3x4 @cpu(0)>

In [149]:
print(x.shape)

(2, 2)


In [155]:
x = x.reshape(shape=(4,1))
y = y.reshape(shape=(4,1))



Traceback (most recent call last):
  Input In [155] in <cell line: 2>
    y = y.reshape(shape=(4,1))
  File /opt/conda/lib/python3.8/site-packages/mxnet/ndarray/ndarray.py:1524 in reshape
    raise ValueError('Cannot reshape array of size {} into shape {}'.format(np.prod(self.shape), shape))
ValueError: Cannot reshape array of size 40 into shape (4, 1)

Use %tb to get the full traceback.


In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torchvision.datasets import MNIST
from torchvision.transforms import ToTensor

# Set device to GPU if available, otherwise use CPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Define neural network architecture
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 32, 3)
        self.conv2 = nn.Conv2d(32, 64, 3)
        self.pool = nn.MaxPool2d(2)
        self.fc1 = nn.Linear(64 * 12 * 12, 128)
        self.fc2 = nn.Linear(128, 10)

    def forward(self, x):
        x = self.pool(torch.relu(self.conv1(x)))
        x = self.pool(torch.relu(self.conv2(x)))
        x = x.view(-1, 64 * 12 * 12)
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# Load MNIST dataset and preprocess data
train_data = MNIST('data', train=True, download=True, transform=ToTensor())
test_data = MNIST('data', train=False, download=True, transform=ToTensor())

# Set up data loaders
train_loader = DataLoader(train_data, batch_size=64, shuffle=True)
test_loader = DataLoader(test_data, batch_size=64, shuffle=False)

# Define loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(net.parameters(), lr=0.001)

# Train neural network
net = Net().to(device)
for epoch in range(10):
    running_loss = 0.0
    for i, data in enumerate(train_loader, 0):
        inputs, labels = data
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = net(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
        if i % 100 == 99:
            print('[%d, %5d] loss: %.3f' % (epoch + 1, i + 1, running_loss / 100))
            running_loss = 0.0

print('Finished training')

# Test neural network
correct = 0
total = 0
with torch.no_grad():
    for data in test_loader:
        inputs, labels = data
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = net(inputs)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print('Accuracy on test set: %d %%' % (100 * correct / total))


  0%|          | 0/9912422 [00:00<?, ?it/s]

Extracting data/MNIST/raw/train-images-idx3-ubyte.gz to data/MNIST/raw



  0%|          | 0/28881 [00:00<?, ?it/s]

Extracting data/MNIST/raw/train-labels-idx1-ubyte.gz to data/MNIST/raw



  0%|          | 0/1648877 [00:00<?, ?it/s]

Extracting data/MNIST/raw/t10k-images-idx3-ubyte.gz to data/MNIST/raw



  0%|          | 0/4542 [00:00<?, ?it/s]

Extracting data/MNIST/raw/t10k-labels-idx1-ubyte.gz to data/MNIST/raw

Traceback (most recent call last):
  Input In [1] in <cell line: 39>
    optimizer = optim.Adam(net.parameters(), lr=0.001)
NameError: name 'net' is not defined

Use %tb to get the full traceback.
